[Task-7] Move Repositories to MongoDB+Mongoose
Shagon1k/nodejs-course pull request #7
Opened 2024-04-07 13:48 UTC by Shagon1k

Check **README** -> *"Application Pre-setup"* for pre-setup details.

2024-04-15 12:13 UTC, Anton-Koniouchevsky requested changes

2024-04-15 12:13 UTC, Anton-Koniouchevsky commented on task-7/src/api/repositories/cart.repository.ts
> +  if (cartItemIndex === -1 && count > 0) {
The same issue as in the previous task. When we have one item in the cart and send put request with count=0 for another item the first item is removed from the cart

2024-04-15 12:13 UTC, Anton-Koniouchevsky commented on task-7/src/scripts/init-db.ts
> +      `mongodb://${DB_USER_USERNAME}:${DB_USER_PASSWORD}@localhost:27017/${DB_NAME}`
it would be great to store localhost and 27017 as env variables for dev environment.

Also please keep in mind that in real life we need to support different kinds of environments (dev/qa/stage/prod/...) so we need a mechanism to define exclusive sets of variables for each of them
https://dheerajgambhir.medium.com/how-to-handle-multiple-environments-in-the-node-js-framework-bb125bc510ef

2024-04-15 12:13 UTC, Anton-Koniouchevsky commented on task-7/src/index.ts
> +dotenv.config({ path: "../.env" });
dotenv.config({ path: path.resolve(__dirname, '../.env') });

2024-04-15 12:21 UTC, Shagon1k commented on task-7/src/api/repositories/cart.repository.ts
> +  if (cartItemIndex === -1 && count > 0) {
`count > 0` should be moved down into separate condition with "`else {return}`" for the case when new item added with count 0.

2024-04-16 11:49 UTC, Shagon1k commented on task-7/src/api/repositories/cart.repository.ts
> +  if (cartItemIndex === -1 && count > 0) {
Fixed. At previous task as well.

2024-04-16 11:49 UTC, Shagon1k commented on task-7/src/scripts/init-db.ts
> +      `mongodb://${DB_USER_USERNAME}:${DB_USER_PASSWORD}@localhost:27017/${DB_NAME}`
Fixed. Thank you!

2024-04-16 11:49 UTC, Shagon1k commented on task-7/src/index.ts
> +dotenv.config({ path: "../.env" });
Fixed

2024-04-18 07:11 UTC, merged